# Ein Ausf端hrungsfehler wird abgefangen
import math

zahl = input("Gib eine Zahl ein ")

# Jetzt soll die Quadratwurzel gezogen werden
# Welche Sorte von Ausf端hrungsfehler (Exception) tritt hier auf?
try:
    wurzel = math.sqrt(zahl)
except:
    print("!!! Fehler bei der Berechnung !!!")
    wurzel = 0

# Dieser Befehl wird nicht mehr ausgef端hrt, da die Programmausf端hrung vorher abbricht
print("Das Ergebnis ist %.2f" % wurzel)